### ISSUE TITLE
执行任何翻译都会弹出以下错误

### ISSUE THREAD

**Issue by terfation** [linghaihui/vim-youdao-translator#4]
Error detected while processing function <SNR>83_visual_translate[1]..<SNR>83_translate[16].
.util#md5[16]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 6 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 3, in <module>
AttributeError: 'LegacyVim' object has no attribute 'bindeval'
Error invoking 'python_eval' on channel 6 (python3-script-host):
error caught in request handler 'python_eval ['res']':
Traceback (most recent call last):
  File "/home/terfation/.local/lib/python3.10/site-packages/pynvim/plugin/script_host.py", l
ine 167, in python_eval
    return eval(expr, self.module.__dict__)
  File "<string>", line 1, in <module>
NameError: name 'res' is not defined

**Comment by bujnlc8** [comment]
暂不支持neovim

**Comment by zbhover** [comment]
```
function! util#md5(s)
    if executable('md5')
        return substitute(system('echo -n "'.a:s.'" | md5'), '\n', '', 'g')
```
这段代码中的md5不是可执行文件，应改为md5sum
```
function! util#md5(s)
    if executable('md5sum')
        return substitute(system('echo -n "'.a:s.'" | md5sum'), '\n', '', 'g')
```

**Comment by iamqqz** [comment]
支持windows平台吗

**Comment by iamqqz** [comment]
支持windows吗？我在ubuntu上可以，windows上报错；

**Comment by iamqqz** [comment]
我在ubuntu上可以用；
windows上报错，
![image](https://github.com/bujnlc8/vim-translator/assets/26315047/629f08ab-baea-4fcb-93a3-9aafcb4f4029)
其他命令报错没有看到报错信息；就是在任务栏快速闪过几次启动什么进程的任务。
:Tr 可以看到这个报错；我是windows 11 64；gvim 9.1-32位
![image](https://github.com/bujnlc8/vim-translator/assets/26315047/f3b0ba3b-5086-49cf-b62d-38bc0e248728)

**Comment by bujnlc8** [comment]
在.vimrc设置`let g:translator_cache=0`试试 @iamqqz
